os:
  - linux

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

cache:
    apt: true
    directories:
        - $HOME/.cache/pip

# For PyQt 4 Mimicking this Travis build: https://travis-ci.org/Asvel/pygs/jobs/42198306
# For manual installation copy this:
# Install PyQt4 from: https://stackoverflow.com/questions/35513019/install-pyqt4-with-python3-on-travis-ci
addons:
  apt:
    packages:
      # For PyQt4
      - libqt4-dev
      - libglu1-mesa-dev
      - mesa-common-dev
      - libgl1-mesa-dev
      - python-qt4
      - python-qt4-dev
      - python-sip
      - python-sip-dev

before_install:
  # For PyQt5
  #- sudo apt-add-repository ppa:beineri/opt-qt551 -y
  #- sudo apt-get update
  #- sudo apt-get install qt-latest
  #- source /opt/qt55/bin/qt55-env.sh
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds

branches:
  except:
    - "/^dev-.+$/"

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install PyQt5 from: https://stackoverflow.com/questions/35019662/how-can-i-install-python3-and-pyqt5-on-travis
  #- sudo mkdir -p /builds && sudo chmod a+rw /builds
  #- sudo mkdir -p /downloads && sudo chmod a+rw /downloads
  #- curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.tar.gz
  #- curl -L -o /downloads/pyqt.tar.gz https://downloads.sourceforge.net/project/pyqt/PyQt5/PyQt-5.8.2/PyQt5_gpl-5.8.2.tar.gz
  #- tar xzf /downloads/sip.tar.gz -C /builds --keep-newer-files
  #- tar xzf /downloads/pyqt.tar.gz -C /builds --keep-newer-files
  #- cd /builds/sip-4.17 && python configure.py && sudo make && sudo make install
  #- cd /builds/PyQt5_gpl-5.8.2 && python configure.py --confirm-license && sudo make && sudo make install
  # Builds Complete
  - pip install tox-travis coveralls
  - pip install .[tests]

script:
  - tox

# Now run coveralls for main supported python version only once.
after_success:
    - if [[ $ENV == python=2.7* ]]; then coveralls; fi

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  repo: AndresMWeber/Nomenclate
  user: andresmweber
  password:
    secure: OaTjXC11whIUCljWbH+UNk2x002DuNlLKrGG7TtDYyStgGqiDzSZcFLUSPEBgqW3luX6UXBwpnP1UPopHSYSBgEWz22PbnR8VwTSdXWFHTcQEvYZvMvd2BFzJK/bYpcARPjVLBkgXF/lmEFNjjyf/+xsjBnO6r8VvYu4Z+dGbCjrqKVLwwQYlBvnGsoHFwESPlar3sIGUtAllNvg+ODczFfZp/clOD3eh2SR6EXov+0iAqiDpCo94sELFlUUzQCcgNZTcLn3tR82r8GQsmRm7kMCyol6ETMEAvTyKuKPGQnFLofhZ9l2MBAuaV4+di/1NhtyWc0WvTTPzh+5qRF9G4qwGo7yh4OWV0otk/n3vwVvZv89h1j6MeB+8jyWjn9oN3B1wHljzVVUmnjTUaEcv8fCBsu0tYMdGtiA+xrqCGqsvgGSAGSysm9xHFh0GupyY/63sKsX8aM4NzMScncAitP3dd0jyHOC3F3x4GUQ0ifO3RuIN2oMlFu8Hpso53yZghoZsbFf/qF4SGSIoYoPrHXrCZfrMOsp4Hfh918gz7K5UGCHeV3HJk2EptWYXDrblhBYDcebOndc0i5MUEc+e116KPliHDHk8Ypd8Y9X1MohKy2gEookGQwNVfkGiRlVAHPRn87Wd4Uvt2/g5vzlNKas5hbng5sxwIiwlvBvIn0=
  on:
    tags: true
  skip_upload_docs: true

notifications:
  slack:
    rooms:
      - andresrules:YFZedni7L0ayOhn3SsX2vQI5
    template:
      - "%{repository} (%{commit}) %{build_number} (%{branch} - %{commit}: %{author}): %{message} "
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Results : %{result}"
