os:
  - linux

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz -o /downloads/sip.tar.gz
  - curl -L http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz -o /downloads/pyqt4.tar.gz
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds

branches:
  except:
    - "/^dev-.+$/"

# Install PyQt4 from: https://stackoverflow.com/questions/35513019/install-pyqt4-with-python3-on-travis-ci
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libqt4-dev
  - sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
#    - sudo apt-get install -y python3-sip python3-sip-dev python3-pyqt4 cmake
  # Qt4
  - pushd /builds
  # SIP
  - tar xzf /downloads/sip.tar.gz --keep-newer-files
  - pushd sip-4.16.5
  - python configure.py
  - make
  - sudo make install
  - popd
  # PyQt4
  - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
  - pushd PyQt-x11-gpl-4.11.3
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtTest
  - make
  - sudo make install
  - popd
  # Builds Complete
  - pip install tox-travis
  - pip install .[test]

script:
  - tox

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  repo: AndresMWeber/Nomenclate
  user: andresmweber
  password:
    secure: OaTjXC11whIUCljWbH+UNk2x002DuNlLKrGG7TtDYyStgGqiDzSZcFLUSPEBgqW3luX6UXBwpnP1UPopHSYSBgEWz22PbnR8VwTSdXWFHTcQEvYZvMvd2BFzJK/bYpcARPjVLBkgXF/lmEFNjjyf/+xsjBnO6r8VvYu4Z+dGbCjrqKVLwwQYlBvnGsoHFwESPlar3sIGUtAllNvg+ODczFfZp/clOD3eh2SR6EXov+0iAqiDpCo94sELFlUUzQCcgNZTcLn3tR82r8GQsmRm7kMCyol6ETMEAvTyKuKPGQnFLofhZ9l2MBAuaV4+di/1NhtyWc0WvTTPzh+5qRF9G4qwGo7yh4OWV0otk/n3vwVvZv89h1j6MeB+8jyWjn9oN3B1wHljzVVUmnjTUaEcv8fCBsu0tYMdGtiA+xrqCGqsvgGSAGSysm9xHFh0GupyY/63sKsX8aM4NzMScncAitP3dd0jyHOC3F3x4GUQ0ifO3RuIN2oMlFu8Hpso53yZghoZsbFf/qF4SGSIoYoPrHXrCZfrMOsp4Hfh918gz7K5UGCHeV3HJk2EptWYXDrblhBYDcebOndc0i5MUEc+e116KPliHDHk8Ypd8Y9X1MohKy2gEookGQwNVfkGiRlVAHPRn87Wd4Uvt2/g5vzlNKas5hbng5sxwIiwlvBvIn0=
  on:
    tags: true

notifications:
  slack:
    rooms:
      - andresrules:YFZedni7L0ayOhn3SsX2vQI5
    template:
      - "%{repository} (%{commit}) %{build_number} (%{branch} - %{commit}: %{author}): %{message} "
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Results : %{result}"
