sudo: required

language: python

services:
  - docker

python:
  - '2.7'

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35

before_install:
  - docker build -t daemonecles/nomenclate .
  - docker ps -a
  - docker run daemonecles/nomenclate

branches:
  except:
  - "/^dev-.+$/"

install:
  - pip install tox

script:
  - tox

deploy:
  provider: pypi
  user: andresmweber
  password:
    secure: OaTjXC11whIUCljWbH+UNk2x002DuNlLKrGG7TtDYyStgGqiDzSZcFLUSPEBgqW3luX6UXBwpnP1UPopHSYSBgEWz22PbnR8VwTSdXWFHTcQEvYZvMvd2BFzJK/bYpcARPjVLBkgXF/lmEFNjjyf/+xsjBnO6r8VvYu4Z+dGbCjrqKVLwwQYlBvnGsoHFwESPlar3sIGUtAllNvg+ODczFfZp/clOD3eh2SR6EXov+0iAqiDpCo94sELFlUUzQCcgNZTcLn3tR82r8GQsmRm7kMCyol6ETMEAvTyKuKPGQnFLofhZ9l2MBAuaV4+di/1NhtyWc0WvTTPzh+5qRF9G4qwGo7yh4OWV0otk/n3vwVvZv89h1j6MeB+8jyWjn9oN3B1wHljzVVUmnjTUaEcv8fCBsu0tYMdGtiA+xrqCGqsvgGSAGSysm9xHFh0GupyY/63sKsX8aM4NzMScncAitP3dd0jyHOC3F3x4GUQ0ifO3RuIN2oMlFu8Hpso53yZghoZsbFf/qF4SGSIoYoPrHXrCZfrMOsp4Hfh918gz7K5UGCHeV3HJk2EptWYXDrblhBYDcebOndc0i5MUEc+e116KPliHDHk8Ypd8Y9X1MohKy2gEookGQwNVfkGiRlVAHPRn87Wd4Uvt2/g5vzlNKas5hbng5sxwIiwlvBvIn0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: AndresMWeber/Nomenclate

notifications:
  slack:
    secure: W6qu3JNdGHESeu0O2CElCi+oCkPTBZPJd38OKk8WTm1k+8GzmG1R5nvM1o5mzGcLtAlCXbkGMJWGz5eOLdJwzjvfr+zEoZS1x6K96oaaEPjLG7Y/3BwTiXsRUjoOkZr2J7nlc07mx3ip6CHraduXAX7TFr6p9VtNr7hO7ovUIbBdOfor5ue7mT6jJx8O7eBTI1dLaE2Hz9gy5VNdg9dpgtUY09FO+HI4kT8bcOb5pkX/4JjvEj3BYrm4NRFOihTBdaVWeSFm3tPc5VrRjk/Pg+m+mZ0zyEjrdfoSA3C+oR+vWeQDY4mGH5qP0AhghZJO+OJ6lwVyeIqTr06Pt8bfNb/7jLq/GeIFHuhmcHlUcClUziVjdnaRgj84P9D+oRbMNuJ4nNgQ4NnDpa2rg2w/dEGZV6SL4V2sIx4QTvPL2GzBvGtYQ9VqMm9l9z4P96Oucw8PP7/yaryjYdOxuliKkIO0A2q7xegYYP+gTMoB0MtxC01hEVsgVuiYHvb3juBDzFG0N30JZQr9q9WIbnRgp/ZMeOIbPoMAP9nfO5CAGAfkKe08OvQSgev6C/BON5EkK2sdhAKz9hg01G77XyTUN6qMhQYhTjn8cjMndr5N6a7Mee/XFNPLA4vQYaQIpxb/dTRJ0vZ47z6JK9jULU2dQEsEWGWlAK5Mimso9GSrYz0=
    rooms:
    - andresrules:YFZedni7L0ayOhn3SsX2vQI5#general
