version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13

    working_directory: ~/Nomenclate

    steps:
      - run:
          name: install virtualenv and make report dir
          command: mkdir ~/test-results

      - checkout

      - restore_cache:
          keys:
          - v1-requirements-{{ checksum "requirements.txt" }}
          - v1-requirements-

      - run:
          name: install dependencies
          command: make install-deps

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-requirements-{{ checksum "requirements.txt" }}

      - run: |
          echo export TEST_PATH=~/test-results >> "$BASH_ENV"
          echo export PYTHON_VERSION=27 >> "$BASH_ENV"

      - run:
          name: run tests
          command: make test-unit

      - store_test_results:
          path: ~/test-results

      - run:
          name: upload coverage
          command: make upload-coverage

  test_35:
    docker:
      - image: circleci/python:3.5

    working_directory: ~/Nomenclate

    steps:
      - run:
          name: make report dir
          command: mkdir ~/test-results

      - checkout

      - restore_cache:
          keys:
          - v1-requirements-{{ checksum "requirements.txt" }}
          - v1-requirements-

      - run:
          name: install dependencies
          command: make install-deps-py3

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-requirements-{{ checksum "requirements.txt" }}

      - run: |
          echo export TEST_PATH=~/test-results >> "$BASH_ENV"
          echo export PYTHON_VERSION=35 >> "$BASH_ENV"
      - run:
          name: run tests
          command: make test-unit

      - store_test_results:
          path: ~/test-results

  test_36:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/Nomenclate

    steps:
      - run:
          name: make report dir
          command: mkdir ~/test-results

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: make install-deps-py3

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run: |
          echo export TEST_PATH=~/test-results >> "$BASH_ENV"
          echo export PYTHON_VERSION=36 >> "$BASH_ENV"
      - run:
          name: run tests
          command: make test-unit

      - store_test_results:
          path: ~/test-results

  deploy:
    docker:
      - image: circleci/python:2.7.13

    working_directory: ~/Nomenclate

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: make install-deps

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run: echo export GIT_TAG=git describe --tags >> "$BASH_ENV"
      - run:
          name: verify git tag vs. version
          command: make verify-git-tag

      - run:
          name: init .pypirc
          command: make init-pypirc

      - run:
          name: create packages
          command: make package

      - run:
          name: upload to pypi
          command: make upload-to-pypi



workflows:
  version: 2
  test_python_versions:
    jobs:
      - build
      - test_35
      - test_36
      - deploy:
          requires:
            - build
            - test_35
            - test_36
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/