version: 2.1
jobs:
  test:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<<parameters.python-version>>

    working_directory: ~/Nomenclate

    steps:
      - run:
          name: make report dir
          command: mkdir ~/test-results

      - checkout

      - restore_cache:
          keys:
            - v1-requirements-{{ checksum "poetry.lock" }}

      - run:
          name: install dependencies
          command: poetry install

      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: v1-requirements-{{ checksum "poetry.lock" }}

      - run:
          name: run tests
          command: |
            poetry run poe test
            poetry run coveralls

      - store_test_results:
          path: ~/test-results

  deploy:
    docker:
      - image: cimg/python:3.8

    working_directory: ~/Nomenclate

    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
  test_and_deploy_on_tags:
    jobs:
      - test:
          matrix:
            parameters:
              python-version: ["3.6", "3.7", "3.8"]
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
