version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13

    working_directory: ~/Nomenclate

    steps:
      - run:
          name: install virtualenv and make report dir
          command: |
              pip install virtualenv
              mkdir ~/test-results

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
              python -m virtualenv ~/nomenclate_venv
              . ~/nomenclate_venv/bin/activate
              pip install -r requirements.txt
              pip install coveralls nose

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:  echo export TEST_PATH=~/test-results >> "$BASH_ENV"
      - run:
          name: run tests
          command: |
            . ~/nomenclate_venv/bin/activate
            nosetests -c tests/nose.cfg --with-coverage --nologcapture --with-xunit --xunit-file=$TEST_PATH/noselog27.xml --cover-package=nomenclate

      - store_test_results:
          path: ~/test-results

      - run:
          name: upload coverage
          command: |
              . ~/nomenclate_venv/bin/activate
              coveralls

  test_35:
    docker:
      - image: circleci/python:3.5

    working_directory: ~/Nomenclate

    steps:
      - run:
          name: install virtualenv and make report dir
          command: |
              pip install virtualenv
              mkdir ~/test-results

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
              python -m virtualenv ~/nomenclate_venv
              . ~/nomenclate_venv/bin/activate
              pip install -r requirements.txt
              pip install coveralls nose

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:  echo export TEST_PATH=~/test-results >> "$BASH_ENV"
      - run:
          name: run tests
          command: |
              . ~/nomenclate_venv/bin/activate
              nosetests -c tests/nose.cfg --with-coverage --nologcapture --with-xunit --xunit-file=$TEST_PATH/noselog35.xml --cover-package=nomenclate

      - store_test_results:
          path: ~/test-results

  test_36:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/Nomenclate

    steps:
      - run:
          name: install virtualenv and make report dir
          command: |
              pip install virtualenv
              mkdir ~/test-results

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m virtualenv ~/nomenclate_venv
            . ~/nomenclate_venv/bin/activate
            pip install -r requirements.txt
            pip install coveralls nose

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:  echo export TEST_PATH=~/test-results >> "$BASH_ENV"
      - run:
          name: run tests
          command: |
            . ~/nomenclate_venv/bin/activate
            echo $TEST_PATH
            nosetests -c tests/nose.cfg --with-coverage --nologcapture --with-xunit --xunit-file=$TEST_PATH/noselog36.xml --cover-package=nomenclate

      - store_test_results:
          path: ~/test-results

  deploy:
    docker:
      - image: circleci/python:2.7.13

    working_directory: ~/Nomenclate

    steps:
      - run: pip install virtualenv

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m virtualenv ~/nomenclate_venv/
            . ~/nomenclate_venv/bin/activate
            pip install -r requirements.txt
            pip install coveralls nose

      - save_cache:
          paths:
            - ~/nomenclate_venv/
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: verify git tag vs. version
          command: |
            python -m virtualenv ~/nomenclate_venv/
            . ~/nomenclate_venv/bin/activate
            python setup.py verify

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
        name: create packages
        command: make package

      - run:
        name: upload to pypi
        command: |
          . ~/nomenclate_venv/bin/activate
          twine upload dist/*


workflows:
  version: 2
  test_python_versions:
    jobs:
      - build
      - test_35:
        requires:
          - build
      - test_36:
        requires:
          - build
      - deploy:
          requires:
            - build
            - test35
            - test36
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/